openapi: 3.0.0
info:
  title: 'L5 OpenApi'
  description: 'L5 Swagger OpenApi description'
  version: 1.0.0
paths:
  /:
    get:
      description: 'Home page'
      operationId: 38f43b9a0d4dde967e301c4f18ea34e5
      responses:
        default:
          description: 'Welcome page'
  '/projects/{id}':
    delete:
      tags:
        - Projects
      summary: 'Delete existing project'
      description: 'Deletes a record and returns no content'
      operationId: deleteProject
      parameters:
        -
          name: id
          in: path
          description: 'Project id'
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 'Successful operation'
          content:
            application/json:
              schema: {  }
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: 'Resource Not Found'
